# Generated by Django 4.2.7 on 2023-11-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=50)),
                ('APELLIDOS', models.CharField(max_length=50)),
                ('CORREO', models.CharField(max_length=50)),
                ('EDAD', models.IntegerField()),
                ('USUARIO', models.CharField(max_length=50)),
                ('CLAVE', models.CharField(max_length=50)),
            ],
        ),
    ]
