# Generated by Django 4.2.7 on 2023-11-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaDos',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=50)),
                ('PRECIO', models.FloatField()),
                ('CATEGORIA', models.CharField(max_length=50)),
                ('DESCRIPCION', models.CharField(max_length=500)),
                ('IMG', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='categoriaUno',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=50)),
                ('PRECIO', models.FloatField()),
                ('CATEGORIA', models.CharField(max_length=50)),
                ('DESCRIPCION', models.CharField(max_length=500)),
                ('IMG', models.CharField(max_length=50)),
            ],
        ),
    ]
